# Generated by Django 4.1 on 2022-09-21 14:01

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='cpf')),
                ('setor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('n_serie', models.IntegerField(unique=True)),
                ('quantidade', models.IntegerField()),
                ('status', models.CharField(choices=[('D', 'Disponivel'), ('E', 'Emprestado'), ('I', 'Indisponivel')], default='Disponivel', max_length=1, null=True)),
                ('observacao', models.TextField(max_length=300)),
            ],
        ),
    ]
