# Generated by Django 4.0.6 on 2022-09-06 03:36

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, unique=True, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='setor',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
