# Generated by Django 4.1 on 2022-10-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('Disponivel', 'Disponivel'), ('Emprestado', 'Emprestado'), ('Indisponivel', 'Indisponivel')], default='Disponivel', max_length=100, null=True),
        ),
    ]
